version: '2'
services:
  cert:
    build: cert
    volumes:
      - cert-data:/etc/private/ssl
    environment:
      SERVERNAME: "${SERVERNAME}"

  postfix-base:
    build: postfix-base
    image: postfix-base:latest
    volumes:
      - postfix-data-spool:/var/spool/postfix
      - postfix-data-sa:/var/lib/spamassassin
      - postfix-data-clamav:/var/lib/clamav
    tty: false

  dovecot-base:
    build: dovecot-base
    image: dovecot-base:latest
    tty: false

  openldap-initial:
    build: openldap-initial
    volumes:
      - ldap-data-etc:/etc/ldap
      - ldap-data:/var/lib/ldap
    environment:
      DEFAULT_DOMAIN: "${DEFAULT_DOMAIN}"
      DEFAULT_USER: "${DEFAULT_USER}"
      BASE_DN: "${BASE_DN}"
      DEFAULT_CN: "${DEFAULT_CN}"
      DEFAULT_SN: "${DEFAULT_SN}"

  postfix:
    build: postfix
    volumes:
      - cert-data:/etc/private/ssl
      - postfix-data-spool:/var/spool/postfix
      - postfix-data-sa:/var/lib/spamassassin
      - postfix-data-clamav:/var/lib/clamav
    tty: true
    links:
      - openldap:ldap
      - dovecot:dovecot
    depends_on:
      - openldap
      - cert
    ports:
      - "25:25"
      - "587:587"
    environment:
      BASE_DN: "${BASE_DN}"
      POSTFIX_DOMAIN: "${DEFAULT_DOMAIN}"
      POSTMASTER: "${POSTMASTER}"
      POSTFIX_LDAP_USER: "cn=Admin"
      POSTFIX_LDAP_PASS: "${SLAPD_PASSWORD}"
      SERVERNAME: "${SERVERNAME}"
      POSTMASTER: "${POSTMASTER}"

  dovecot:
    build: dovecot
    volumes:
      - cert-data:/etc/private/ssl
      - mail-data:/vmail
    tty: true
    depends_on:
      - openldap
      - cert
      - dovecot-base
    links:
      - openldap:ldap
    ports:
      - "143:143"
      - "993:993"
    environment:
      BASE_DN: "${BASE_DN}"
      DOVECOT_LDAP_USER: "cn=Admin"
      DOVECOT_LDAP_PASS: "${SLAPD_PASSWORD}"
      SERVERNAME: "${SERVERNAME}"

  openldap:
    image: dinkel/openldap
    labels:
      io.rancher.sidekicks: openldap-initial
    volumes:
      - ldap-data-etc:/etc/ldap
      - ldap-data:/var/lib/ldap
      - cert-data:/etc/private/ssl
    environment:
      SLAPD_CONFIG: "${SLAPD_DOMAIN}"
      SLAPD_PASSWORD: "${SLAPD_PASSWORD}"
      SLAPD_CONFIG_PASSWORD: "${SLAPD_PASSWORD}"
      SLAPD_ADDITIONAL_SCHEMAS: ppolicy,opendkim,postfix
      SLAPD_DOMAIN: "${SLAPD_DOMAIN}"
    depends_on:
      - openldap-initial
      - cert
    ports:
      - "389:389"

volumes:
  cert-data:
  ldap-data:
  ldap-data-etc:
  mail-data:
  postfix-data-spool:
  postfix-data-sa:
  postfix-data-clamav:

