version: '2'
services:
  ldap-data:
    image: busybox
    volumes:
      - /etc/ldap
      - /var/lib/ldap

  mail-data:
    image: busybox
    volumes:
      - /vmail

  postfix-data:
    image: busybox
    volumes:
      - /var/spool/postfix
      - /var/lib/spamassassin
      - /var/lib/clamav

  postfix-base:
    build: postfix-base
    image: postfix-base:latest
    volumes_from:
      - postfix-data
    tty: false

  dovecot-base:
    build: dovecot-base
    image: dovecot-base:latest
    tty: false

  openldap-initial:
    volumes_from:
      - ldap-data
    build: openldap-initial
    environment:
      POSTFIX_DOMAIN: "${SLAPD_DOMAIN}"
      BASE_DN: "${BASE_DN}"

  postfix:
    build: postfix
    volumes_from:
      - postfix-data
    tty: true
    links:
      - openldap:ldap
      - dovecot:dovecot
    ports:
      - "25:25"
      - "587:587"
    environment:
      BASE_DN: "${BASE_DN}"
      POSTFIX_DOMAIN: "${SLAPD_DOMAIN}"
      POSTFIX_LDAP_USER: "cn=Admin"
      POSTFIX_LDAP_PASS: "${SLAPD_PASSWORD}"

  dovecot:
    build: dovecot
    volumes_from:
      - mail-data
    tty: true
    links:
      - openldap:ldap
    ports:
      - "143:143"
    environment:
      BASE_DN: "${BASE_DN}"
      DOVECOT_LDAP_USER: "cn=Admin"
      DOVECOT_LDAP_PASS: "${SLAPD_PASSWORD}"

  openldap:
    image: dinkel/openldap
    labels:
      io.rancher.sidekicks: openldap-initial
    volumes_from:
      - ldap-data
    environment:
      SLAPD_CONFIG: "${SLAPD_DOMAIN}"
      SLAPD_PASSWORD: "${SLAPD_PASSWORD}"
      SLAPD_CONFIG_PASSWORD: "${SLAPD_PASSWORD}"
      SLAPD_ADDITIONAL_SCHEMAS: ppolicy,opendkim,postfix
      SLAPD_DOMAIN: "${SLAPD_DOMAIN}"
    depends_on:
      - openldap-initial
    ports:
      - "389:389"