version: '2'
services:
  ldap-data:
    image: busybox
    volumes:
      - /etc/ldap
      - /var/lib/ldap

  postfix-data:
    image: busybox
    volumes:
      - /var/spool/postfix

  openldap-initial:
    volumes_from:
      - ldap-data
    build: ldap-schema

  postfix:
    build: postfix
    volumes_from:
      - postfix-data
    tty: true
    links:
      - openldap:ldap
    ports:
      - "25:25"

  openldap:
    image: dinkel/openldap
    labels:
      io.rancher.sidekicks: openldap-initial
    volumes_from:
      - ldap-data
    links:
      - openldap-initial
    environment:
      SLAPD_CONFIG: "${SLAPD_DOMAIN}"
      SLAPD_PASSWORD: "${SLAPD_PASSWORD}"
      SLAPD_CONFIG_PASSWORD: "${SLAPD_PASSWORD}"
      SLAPD_ADDITIONAL_SCHEMAS: ppolicy,opendkim,postfix
      SLAPD_DOMAIN: "${SLAPD_DOMAIN}"
      depends_on:
        openldap-initial
    ports:
      - "389:389"